code:
  image: busybox
  volumes:
    - '.:/app/wowfeed'
dev:
  build: .
  command: 'bash -c "(coffee --compile --watch --output js/ src/ spec/ src_common) & (coffee --compile --watch --output public/js-cs src_client src_common) & while true; do echo `date`: still here; sleep 10; done"'
  working_dir: /app/wowfeed
  environment:
    MONGOLAB_URI: 'mongolab:27017'
    wowPublicKey:
  volumes_from:
    - code
  links:
    - mongolab
  stdin_open: true
  tty: true
test:
  build: .
  # command: 'bash -c ''(coffee --compile --watch --output js/ src/ spec/ src_common) & (coffee --compile --watch --output public/js-cs src_client src_common) & (mocha --watch -g "get all realms 1" js/wowlookupSpec.js) & while true; do echo `date`: still here; sleep 10; done '''
  command: 'bash -c ''(coffee --compile --watch --output js/ src/ spec/ src_common) & (coffee --compile --watch --output public/js-cs src_client src_common) & (mocha --watch js/wowlookupSpec.js) & while true; do echo `date`: still here; sleep 10; done '''
  working_dir: /app/wowfeed
  environment:
    MONGO_HOST: mongolab
    MONGO_PORT: 27017
    MONGO_DB: wowfeed
    wowPublicKey:
  volumes_from:
    - code
  links:
    - mongolab
  stdin_open: true
  tty: true
web:
  build: .
  command: 'bash -c ''./run_server.sh && while true; do echo `date`: still here; sleep 10; done '''
  volumes_from:
    - code
  working_dir: /app/wowfeed
  environment:
    PORT: 8080
    MONGOLAB_URI: 'mongolab:27017'
    MONGO_HOST: mongolab
    MONGO_PORT: 27017
    MONGO_DB: wowfeed
    wowPublicKey:
    WAF_CONSUMER_KEY:
    WAF_CONSUMER_SECRET:
    WAF_ACCESS_TOKEN:
    WAF_ACCESS_TOKEN_SECRET:
  ports:
    - '8080:3000'
  links:
    - mongolab
  stdin_open: true
  tty: true
webdev:
  build: .
  command: 'bash -c ''(coffee --compile --watch --output js/ src/ spec/ src_common) & (coffee --compile --watch --output public/js-cs src_client src_common) & nodemon app.js & while true; do echo `date`: still here; sleep 10; done '''
  volumes_from:
    - code
  working_dir: /app/wowfeed
  environment:
    PORT: 8080
    MONGOLAB_URI: 'mongolab:27017'
    MONGO_HOST: mongolab
    MONGO_PORT: 27017
    MONGO_DB: wowfeed
    wowPublicKey:
  ports:
    - '8080:3000'
  links:
    - mongolab
  stdin_open: true
  tty: true
mongolab:
  image: mongo:2.4.14
